"""One-command release for MagneMotion Monitor.

Version scheme: WEEK.DAY.BUILD
  WEEK  = ISO week of the year (1-53)
  DAY   = ISO weekday (1=Mon … 7=Sun)
  BUILD = build counter for that day; resets to 1 each new day, +1 on rebuilds

    python release.py            # bump version, then build dist/MagneMotionMonitor.exe
    python release.py --no-build # just bump mm_monitor/version.py
"""
from __future__ import annotations
import datetime as _dt
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
VERSION_FILE = ROOT / "mm_monitor" / "version.py"


def _today_week_day() -> tuple[int, int]:
    iso = _dt.date.today().isocalendar()
    return iso.week, iso.weekday          # weekday: 1=Mon … 7=Sun


def _current() -> tuple[int, int, int] | None:
    if not VERSION_FILE.exists():
        return None
    m = re.search(r'VERSION\s*=\s*"(\d+)\.(\d+)\.(\d+)"',
                  VERSION_FILE.read_text(encoding="utf-8"))
    return (int(m.group(1)), int(m.group(2)), int(m.group(3))) if m else None


def bump() -> str:
    week, day = _today_week_day()
    cur = _current()
    build = cur[2] + 1 if (cur and cur[0] == week and cur[1] == day) else 1
    version = f"{week}.{day}.{build}"
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    VERSION_FILE.write_text(
        '"""Auto-generated by release.py - do not edit by hand."""\n'
        f'VERSION = "{version}"\n'
        f'BUILD_DATE = "{stamp}"\n',
        encoding="utf-8",
    )
    print(f"Version -> {version}  ({stamp})")
    return version


def build_exe():
    print("Building EXE …")
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
         "MagneMotionMonitor.spec"],
        cwd=ROOT, check=True,
    )
    print("Built dist/MagneMotionMonitor.exe")


if __name__ == "__main__":
    bump()
    if "--no-build" not in sys.argv:
        build_exe()
