"""One-command release for MagneMotion Monitor.

Version scheme: WEEK.DAY.BUILD
  WEEK  = ISO week of the year (1-53)
  DAY   = ISO weekday (1=Mon … 7=Sun)
  BUILD = build counter for that day; resets to 1 each new day, +1 on rebuilds

    python release.py            # bump version, build, commit + push to GitHub
    python release.py --no-build # just bump mm_monitor/version.py
    python release.py --no-push  # bump + build, but skip the git commit/push
    python release.py --no-git   # alias for --no-push

Requires a git remote already configured (`git remote add origin ...` or
`gh repo create ... --push` once, up front) — if there isn't one yet, the git
step prints a note and is skipped rather than failing the whole release.
"""
from __future__ import annotations
import datetime as _dt
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
VERSION_FILE = ROOT / "mm_monitor" / "version.py"


def _today_week_day() -> tuple[int, int]:
    iso = _dt.date.today().isocalendar()
    return iso.week, iso.weekday          # weekday: 1=Mon … 7=Sun


def _current() -> tuple[int, int, int] | None:
    if not VERSION_FILE.exists():
        return None
    m = re.search(r'VERSION\s*=\s*"(\d+)\.(\d+)\.(\d+)"',
                  VERSION_FILE.read_text(encoding="utf-8"))
    return (int(m.group(1)), int(m.group(2)), int(m.group(3))) if m else None


def bump() -> str:
    week, day = _today_week_day()
    cur = _current()
    build = cur[2] + 1 if (cur and cur[0] == week and cur[1] == day) else 1
    version = f"{week}.{day}.{build}"
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    VERSION_FILE.write_text(
        '"""Auto-generated by release.py - do not edit by hand."""\n'
        f'VERSION = "{version}"\n'
        f'BUILD_DATE = "{stamp}"\n',
        encoding="utf-8",
    )
    print(f"Version -> {version}  ({stamp})")
    return version


def build_exe():
    print("Building EXE …")
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
         "MagneMotionMonitor.spec"],
        cwd=ROOT, check=True,
    )
    print("Built dist/MagneMotionMonitor.exe")


def build_exe_fast():
    """Incremental build: reuse PyInstaller cache. Much faster than --clean."""
    print("Building EXE (fast/incremental) …")
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--noconfirm",
         "MagneMotionMonitor.spec"],
        cwd=ROOT, check=True,
    )
    print("Built dist/MagneMotionMonitor.exe")


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)


def git_publish(version: str):
    """Stage everything, commit as this release, and push to the configured
    remote. Never raises — a git problem (no remote yet, network down, nothing
    changed) prints a clear note and returns, so it can't turn a successful
    EXE build into a failed release run."""
    if not (ROOT / ".git").exists():
        print("Not a git repository — skipping commit/push. Run "
              "'git init' and add a remote (or 'gh repo create --push') once, "
              "then re-run release.py.")
        return

    remote = _git("remote", "get-url", "origin")
    if remote.returncode != 0:
        print("No 'origin' remote configured — skipping push. Run once:\n"
              "  gh repo create <name> --private --source=. --remote=origin --push")
        return

    add = _git("add", "-A")
    if add.returncode != 0:
        print(f"git add failed, skipping commit/push:\n{add.stderr}")
        return

    if _git("diff", "--cached", "--quiet").returncode == 0:
        print("No changes to commit — nothing to push.")
        return

    commit = _git("commit", "-m", f"Release v{version}")
    if commit.returncode != 0:
        print(f"git commit failed, skipping push:\n{commit.stderr}")
        return

    branch = _git("branch", "--show-current").stdout.strip() or "main"
    has_upstream = _git("rev-parse", "--abbrev-ref", f"{branch}@{{u}}").returncode == 0
    push_args = ["push"] if has_upstream else ["push", "-u", "origin", branch]
    push = _git(*push_args)
    if push.returncode != 0:
        print(f"git push failed:\n{push.stderr}\n"
              "(the EXE built fine — this only affects publishing to GitHub)")
        return

    print(f"Pushed v{version} to GitHub ({branch}).")


if __name__ == "__main__":
    version = bump()
    if "--no-build" not in sys.argv:
        if "--fast" in sys.argv:
            build_exe_fast()
        else:
            build_exe()
    if "--no-push" not in sys.argv and "--no-git" not in sys.argv:
        git_publish(version)
